// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectAPITest.Context;

#nullable disable

namespace ProjectAPITest.Migrations
{
    [DbContext(typeof(ProjectApiContextContext))]
    partial class ProjectApiContextContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjectAPITest.Domains.Products", b =>
                {
                    b.Property<Guid>("IdProduct")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdProduct");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            IdProduct = new Guid("f1146f04-4a03-4b9b-a9c4-38aa118d8308"),
                            Name = "Samsung A52s",
                            Price = 2768.90m
                        },
                        new
                        {
                            IdProduct = new Guid("3a6c1b48-00a1-4c3b-96af-33d7025a967b"),
                            Name = "Apple iPhone 15 Pro Max 512 GB -Titânio Natural",
                            Price = 9699m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
